# -*- coding: utf-8 -*-
"""Local service-area pages. Every fact below was checked against a public source (EGLE, NOAA Coast Pilot,
Wayne County, city sites, US Army Corps). Wording is hedged where a detail could not be confirmed.
water: lsc = Lake St. Clair, anchor = Anchor Bay, scr = St. Clair River, dr = Detroit River, erie = Lake Erie, river = tributary river."""

WATERS = {
 'lsc':   dict(label='Lake St. Clair', short='Lake St. Clair', group='Lake St. Clair'),
 'anchor':dict(label='Anchor Bay on Lake St. Clair', short='Anchor Bay', group='Lake St. Clair'),
 'scr':   dict(label='the St. Clair River', short='the St. Clair River', group='St. Clair River'),
 'dr':    dict(label='the Detroit River', short='the Detroit River', group='Detroit River'),
 'erie':  dict(label='Lake Erie and the River Raisin', short='Lake Erie', group='Lake Erie and Tributaries'),
 'river': dict(label='the Huron River', short='the Huron River', group='Lake Erie and Tributaries'),
}
GROUPS = ['Lake St. Clair', 'St. Clair River', 'Detroit River', 'Lake Erie and Tributaries']

TOWNS = [
 dict(slug='st-clair-shores', name='St. Clair Shores', kind='city', county='Macomb', water='lsc', hero='boat-lift-covered-slip',
  lead='Canal-front lots, boat wells and marinas along Lake St. Clair make St. Clair Shores one of Metro Detroit’s busiest boating communities.',
  p1='St. Clair Shores calls itself the Boating Capital of Michigan, and the waterfront backs it up. A network of canals gives many homeowners direct lake access from their backyards, and the Nautical Mile on Jefferson Avenue between Nine and Ten Mile roads is lined with marinas and boat services. Each of those canal lots depends on a seawall, and most also have a dock, boat well or hoist.',
  p2='Canal walls face a different kind of wear than open shoreline. Constant boat traffic, narrow lots and shallow water stress caps, seams and anchors, and silt builds up in boat wells over the years. Because lots are tight, equipment access often decides the plan: work can run from the land side, from a barge in the canal, or both.',
  notes=['St. Clair Shores is in Macomb County on Lake St. Clair.', 'The city has both private and city-owned marinas, concentrated along the Nautical Mile.', 'Many residential lots sit on canals, so seawalls, boat wells, docks and hoists are part of everyday home maintenance.'],
  svc=[('seawalls','Canal and lakefront walls in vinyl, steel, concrete or galvanized systems, with caps, splash guards and French drains.'),('docks','New docks, re-decking, structural repairs and removal.'),('boat-hoists','Hoist installs, cable changes, motor service and welding repairs.'),('dredging','Boat well and canal slip dredging when silt limits depth.'),('pilings','Steel and wood pilings for docks, hoists and walls.')],
  faq=('Can you work on a narrow canal lot in St. Clair Shores?','<p>Yes. Narrow lots change how the job is planned rather than whether it can be done. Depending on the site, equipment can work from the land side, from a barge in the canal, or both. Send photos of the lot and the canal when you request a quote.</p>'),
  near=['grosse-pointe-shores','grosse-pointe-woods','harrison-township']),

 dict(slug='grosse-pointe-shores', name='Grosse Pointe Shores', kind='city', county='Wayne', water='lsc', hero='sheet-pile-excavator-canal-home',
  lead='Open Lake St. Clair frontage in the smallest of the Grosse Pointe communities calls for walls built to handle waves, ice and high water.',
  p1='Grosse Pointe Shores is the smallest of the five Grosse Pointe communities, and it is home to the Edsel and Eleanor Ford House on the lakeshore. Much of the waterfront here is residential property facing open Lake St. Clair rather than sheltered canals.',
  p2='Open frontage takes more wave energy than a canal. When Lake St. Clair reached record highs in 2019 and 2020, waves and high water tested shoreline walls all along the lake. For lakefront owners the practical checklist is sound anchoring, working drainage behind the wall, a solid cap and splash protection at the top, plus concrete and steps that can handle freeze-thaw cycles.',
  notes=['Grosse Pointe Shores is in Wayne County on Lake St. Clair.', 'It is the smallest of the five Grosse Pointe cities, at about 1.1 square miles.', 'Lakefront lots face open water, so wall exposure and ice matter.'],
  svc=[('seawalls','Repairs, cap work, splash guards and full replacements for exposed lakefront walls.'),('concrete','Patios, walks and steps in brushed, exposed aggregate, trowel or stamped finishes.'),('decks','Wood, composite and Trex decks for lake views.'),('welding-fabrication','Custom steel railings and gates.'),('excavating-grading','Grading and drainage work that keeps water away from the wall.')],
  faq=('Does high water on Lake St. Clair affect my seawall in Grosse Pointe Shores?','<p>It can. High water shrinks the distance between the water and the top of the wall, so waves are more likely to wash over the cap and carry soil out from behind it. Splash guards, a sound cap and good drainage help. See our guide to <a href="/blog/great-lakes-water-levels-waterfront-property/">Great Lakes water levels and your waterfront</a>.</p>'),
  near=['grosse-pointe-farms','st-clair-shores','grosse-pointe-woods']),

 dict(slug='grosse-pointe-farms', name='Grosse Pointe Farms', kind='city', county='Wayne', water='lsc', hero='vibratory-hammer-steel-pile',
  lead='Lakefront homes on the “point” of Grosse Pointe face a shoreline that bends toward the east, so wall design starts with how waves reach your lot.',
  p1='Grosse Pointe Farms sits on the shore of Lake St. Clair and contains the actual point of Grosse Pointe, just east of the Grosse Pointe War Memorial, where the lakeshore bends so that the shoreline faces east instead of south. The city’s recreation area includes Pier Park and Pier Park Harbor.',
  p2='Which way a shoreline faces affects how waves and ice reach it, so a wall design should reflect your exact frontage and not a generic template. Older lakefront properties often carry walls that have seen decades of weather. Check the cap, seams, wall ends and the ground behind the wall, and keep drainage clear.',
  notes=['Grosse Pointe Farms is in Wayne County on Lake St. Clair.', 'Pier Park and Pier Park Harbor are on the lakefront.', 'The shoreline bends at “the point,” changing which direction lakefront lots face.'],
  svc=[('seawalls','Inspection-driven repairs and replacements for lakefront walls.'),('pilings','Steel and wood pilings, covers and removal.'),('docks','Docks, repairs and re-decking for private lakefront properties.'),('concrete','Concrete flatwork near the shoreline, with drainage that slopes away from the wall.'),('welding-fabrication','Steel railings, gates and custom fabrication.')],
  faq=('What should I look for on an older lakefront seawall in Grosse Pointe Farms?','<p>Look for leaning, sinking soil or voids behind the wall, open seams, a cracked cap and erosion at the wall ends. Our checklist of <a href="/blog/signs-your-seawall-is-failing/">seawall warning signs</a> walks through each one.</p>'),
  near=['grosse-pointe-shores','grosse-pointe-park','grosse-pointe-woods']),

 dict(slug='grosse-pointe-park', name='Grosse Pointe Park', kind='city', county='Wayne', water='lsc', hero='demolition-excavator-canal',
  lead='Where Lake St. Clair narrows into the Detroit River, Grosse Pointe Park pairs lakefront property with older homes and a busy shoreline.',
  p1='Grosse Pointe Park is where Lake St. Clair ends and the Detroit River begins, and it borders Detroit’s east side. The city is known for historic architecture, including many homes designed before World War II, and Windmill Pointe Park serves as its main lakefront park.',
  p2='Older homes and older shoreline structures tend to go together. Lakefront owners here may be dealing with aging walls, settled patios and worn steps as well as railings and gates that no longer match the house. Because Grosse Pointe Park sits at the river entrance, ask EGLE which part of state law applies to your shoreline before you plan in-water work.',
  notes=['Grosse Pointe Park is in Wayne County at the entrance to the Detroit River.', 'Windmill Pointe Park is the city’s main lakefront park.', 'The city is known for historic homes, many built before World War II.'],
  svc=[('seawalls','Repairs and replacements for aging lakefront walls.'),('concrete','Removal of old slabs and new patios, drives and walks.'),('decks','Wood, composite and Trex decks and repairs.'),('welding-fabrication','Custom railings and gates fabricated to suit older homes.'),('demolition','Concrete removal and demolition of garages and sheds, with hauling.')],
  faq=('Which waterway rules apply to my shoreline in Grosse Pointe Park?','<p>Grosse Pointe Park sits at the point where Lake St. Clair flows into the Detroit River. Permit requirements depend on your exact site, so confirm with EGLE district staff. Work at or below the ordinary high-water mark generally needs an EGLE permit and often an Army Corps permit. See our <a href="/blog/michigan-permits-seawalls-docks-dredging/">Michigan permit guide</a>.</p>'),
  near=['grosse-pointe-farms','grosse-pointe-woods','grosse-pointe-shores']),

 dict(slug='grosse-pointe-woods', h1='Concrete, Decks and Site Work in Grosse Pointe Woods, Michigan', title='Grosse Pointe Woods: Concrete & Decks', desc='Concrete, decks, excavating, demolition and custom steel in Grosse Pointe Woods, Michigan, plus waterfront work on nearby Lake St. Clair. Free quotes.', name='Grosse Pointe Woods', kind='city', county='Wayne', water='lsc', hero='new-concrete-patio',
  lead='Grosse Pointe Woods is the one Pointe without its own Lake St. Clair shoreline, so most projects here are concrete, decks, excavating and steel.',
  p1='Grosse Pointe Woods is the only one of the five Grosse Pointe cities without Lake St. Clair shoreline of its own, though the city owns Lake Front Park in nearby St. Clair Shores, a residents-only park with a boardwalk and dockage. That means seawall and dock work is unusual inside the city itself.',
  p2='What Woods homeowners do need is the work that surrounds a home: new patios and driveways, decks, drainage and grading, demolition of old garages or slabs, and custom steel railings and gates. We also help Woods residents who own or manage waterfront property elsewhere on Lake St. Clair, from a lake home to a boat well.',
  notes=['Grosse Pointe Woods is in Wayne County and has no direct Lake St. Clair shoreline.', 'The city owns Lake Front Park in St. Clair Shores.', 'Residential concrete, decks, grading and fabrication are the most common needs.'],
  svc=[('concrete','Patios, driveways and walkways in four finishes, plus removal of old concrete.'),('decks','Custom decks in wood, composite and Trex.'),('excavating-grading','Site prep, grading and drainage for new construction.'),('demolition','Garages, sheds and slabs removed and hauled.'),('welding-fabrication','Railings, gates and custom metalwork.')],
  faq=('Do you serve Grosse Pointe Woods if I do not have waterfront property?','<p>Yes. Concrete, decks, excavating, grading, demolition and custom fabrication are part of what we do for homes anywhere in Metro Detroit, waterfront or not. If you also own property on the lake or a canal, we can help with seawalls, docks and hoists there too.</p>'),
  near=['grosse-pointe-park','grosse-pointe-farms','st-clair-shores']),

 dict(slug='grosse-ile', name='Grosse Ile', kind='township', county='Wayne', water='dr', hero='barge-boathouse-excavator',
  lead='Grosse Ile is the largest island in the Detroit River, and almost every property on it has a shoreline, a canal or a channel to plan around.',
  p1='Grosse Ile is the largest island in the Detroit River and the most populated island in Michigan. The Trenton Channel runs along its west side, the main river channel along its east side, and two canals divide the island itself. Two bridges, the Grosse Ile Toll Bridge and the Wayne County Bridge, connect it to the mainland.',
  p2='That geography shapes projects. Freighters and pleasure boats pass near the east side, canals and channels bring their own wave and current patterns, and getting equipment onto an island is a planning question in its own right, sometimes solved from the water with a barge. Grosse Ile also sits at the center of the Detroit River International Wildlife Refuge, so ask early how habitat considerations may factor into permit review.',
  notes=['Grosse Ile Township is in Wayne County and includes more than a dozen islands.', 'The Trenton Channel runs along the west side, and the island is divided by two canals.', 'The township sits at the center of the Detroit River International Wildlife Refuge.'],
  svc=[('seawalls','Channel and canal walls built for current, boat wakes and ice.'),('docks','Fixed, floating and custom docks.'),('pilings','Steel and wood pilings for docks and hoists, installed from land or barge.'),('boat-hoists','Lifts for island and canal properties.'),('dredging','Boat well and canal dredging.'),('excavating-grading','Site work and hauling.')],
  faq=('Can you get equipment onto Grosse Ile?','<p>Island access is part of planning every job. The island’s two bridges connect it to the mainland, and barge access from the water can be another option for shoreline work. Tell us your address when you request a quote so we can plan the approach for your site.</p>'),
  near=['trenton','wyandotte','gibraltar']),

 dict(slug='harrison-township', name='Harrison Township', kind='charter township', county='Macomb', water='lsc', hero='barge-excavator-canal',
  lead='With the Clinton River mouth, Lake St. Clair Metropark and dozens of marinas, Harrison Township is built around the water.',
  p1='Harrison Township is often called Boattown, and its geography explains why. The Clinton River empties into Lake St. Clair here, Lake St. Clair Metropark runs along the lakeshore, and the township holds a large number of marinas. Water covers a large share of the township’s total area.',
  p2='Properties near a river mouth deal with sediment that the river carries in, so shallow slips and boat wells are a recurring concern, and canals and marinas add walls, docks and lifts to the mix. Whether you are on the river, a canal or the open lake, wall type, pilings and depth all need to be planned around your specific frontage.',
  notes=['Harrison Township is in Macomb County on Lake St. Clair.', 'The Clinton River has its mouth in the lake within the township.', 'Lake St. Clair Metropark is on the township’s lakeshore.'],
  svc=[('seawalls','Walls along the river, canals and lake in vinyl, steel, concrete or galvanized systems.'),('docks','New docks, repairs and removal.'),('boat-hoists','Hoist installation and maintenance.'),('dredging','Boat well and canal dredging where silt limits depth.'),('pilings','Pilings for docks, hoists and walls.')],
  faq=('Can you dredge a boat well near the Clinton River in Harrison Township?','<p>Yes, dredging boat wells and canals is part of our marine work. Dredging in waters connected to Lake St. Clair generally needs permits, so plan for review time. See our <a href="/blog/dredging-101-canals-marinas-boat-wells/">dredging guide</a> for how projects are planned.</p>'),
  near=['st-clair-shores','chesterfield-township','new-baltimore']),

 dict(slug='new-baltimore', name='New Baltimore', kind='city', county='Macomb', water='anchor', hero='barge-open-water',
  lead='New Baltimore sits on Anchor Bay, a huge but very shallow part of Lake St. Clair where depth is the first question for docks and hoists.',
  p1='New Baltimore is a waterfront city on Anchor Bay, the northern arm of Lake St. Clair. The bay covers more than 90 square miles yet is only about 1 to 11 feet deep, which is unusually shallow for its size. The city has a park with a fishing pier and sandy beach on the bay.',
  p2='Shallow water shapes almost every waterfront decision. Docks may need to run farther out to reach usable depth, boat wells and slips can lose depth to silt, and a hoist has to lower fully clear of the bottom. Wave chop over shallow water and winter ice add stress on pilings and walls.',
  notes=['New Baltimore is in Macomb County on Anchor Bay.', 'Anchor Bay is about 1 to 11 feet deep across most of its area.', 'Docks, boat wells and dredging are common topics for waterfront owners.'],
  svc=[('docks','Docks sized and laid out for shallow water.'),('dredging','Boat well and slip dredging to restore depth.'),('boat-hoists','Lifts matched to your boat and slip depth.'),('seawalls','Repairs and new walls for bayfront and canal lots.'),('pilings','Pilings for fixed docks and hoists.')],
  faq=('How shallow is Anchor Bay, and how does it affect my dock in New Baltimore?','<p>Anchor Bay is only about 1 to 11 feet deep across most of its area. That can mean longer docks to reach usable depth, regular attention to silt in slips and boat wells, and hoists that must lower clear of the bottom. See <a href="/blog/how-to-choose-a-boat-hoist/">how to choose a boat hoist</a> and <a href="/blog/floating-vs-fixed-docks/">floating vs. fixed docks</a>.</p>'),
  near=['chesterfield-township','harrison-township','algonac']),

 dict(slug='chesterfield-township', name='Chesterfield Township', kind='township', county='Macomb', water='anchor', hero='gray-dock-walkway-canal',
  lead='Chesterfield Township borders Anchor Bay, where shallow water, tributary sediment and open-bay waves shape every waterfront project.',
  p1='Chesterfield Township is one of the Macomb County townships that border Anchor Bay, the shallow northern arm of Lake St. Clair. Streams such as the Salt River feed the bay, and the bay drains onward through Lake St. Clair to the Detroit River.',
  p2='Waterfront owners here often need a mix of work: walls and pilings to hold the shoreline, docks that reach usable depth, and dredging or excavating to deal with sediment and drainage. The land side matters too, since grading, concrete and drainage decide whether water is drawn toward or away from the wall.',
  notes=['Chesterfield Township is in Macomb County and borders Anchor Bay.', 'Anchor Bay is very shallow, about 1 to 11 feet deep.', 'Rivers and streams carry sediment into the bay.'],
  svc=[('seawalls','Walls and repairs along the bay and its waterways.'),('docks','Docks and repairs suited to shallow water.'),('dredging','Sediment removal for slips and boat wells.'),('excavating-grading','Grading and drainage for waterfront lots.'),('concrete','Patios, drives and walks near the water.')],
  faq=('Which body of water is my Chesterfield Township property on?','<p>Township waterfront generally sits on Anchor Bay or on streams and canals that connect to it, and Anchor Bay is part of Lake St. Clair. Your survey or permit history shows which applies, and EGLE can confirm the regulatory details for your site.</p>'),
  near=['new-baltimore','harrison-township','algonac']),

 dict(slug='algonac', name='Algonac', kind='city', county='St. Clair', water='scr', hero='excavator-pipe-pilings-dusk',
  lead='Algonac sits where the St. Clair River spreads into the St. Clair Flats delta, so current, ship traffic and island access all come into play.',
  p1='Algonac is on the St. Clair River near where it flows into Lake St. Clair. Harsens, Russell and other islands in the St. Clair Flats, the only major river delta in the Great Lakes, lie just offshore, and car ferries link Algonac to Russell Island and Walpole Island. The city has a waterfront park with a long boardwalk.',
  p2='River conditions differ from lake conditions. NOAA’s Coast Pilot lists St. Clair River currents at Algonac of roughly 1.3 to 2.0 mph depending on flow, and large freighters pass close to shore. Walls and pilings here have to resist steady current and scour as well as wave and ice loads, which is why anchoring and steel pilings get extra attention.',
  notes=['Algonac is in St. Clair County on the St. Clair River.', 'NOAA lists river current at Algonac at about 1.3 to 2.0 mph, depending on flow.', 'The St. Clair Flats delta and its islands are just offshore.'],
  svc=[('seawalls','Walls built for river current, wakes and ice.'),('pilings','Steel and wood pilings, covers and removal.'),('docks','Docks and repairs for river and canal properties.'),('boat-hoists','Hoist installs and maintenance.'),('dredging','Slip and boat well dredging.'),('welding-fabrication','Marine steel repairs and custom fabrication.')],
  faq=('How strong is the current on the St. Clair River at Algonac?','<p>NOAA’s Coast Pilot gives current at Algonac of roughly 1.3 to 2.0 mph depending on river flow. That is enough to affect scour, dock design and boat handling, and freighter wakes add to it. Structures here are designed with that steady flow in mind.</p>'),
  near=['marine-city','new-baltimore','chesterfield-township']),

 dict(slug='marine-city', name='Marine City', kind='city', county='St. Clair', water='scr', hero='barge-excavator-snow',
  lead='Freighters pass close to Marine City’s downtown waterfront, and river ice is part of every winter, so walls and docks here work hard.',
  p1='Marine City sits directly on the St. Clair River, where large ships pass close enough to shore that people come to watch them. Downtown has eight walkable waterfront parks along Water Street, and the river current at Marine City runs roughly 1.3 to 2.0 mph depending on flow, according to NOAA.',
  p2='Steady current, close ship traffic and river ice put continuous demands on shoreline structures. Ice build-up in the St. Clair River is a known winter issue, and it can push on walls, grip pilings and damage docks. Good anchoring, protected steel and a fall inspection routine make the difference.',
  notes=['Marine City is in St. Clair County on the St. Clair River.', 'Eight waterfront parks line Water Street downtown.', 'River ice and passing ships are regular factors for waterfront structures.'],
  svc=[('seawalls','Walls and repairs for river frontage.'),('docks','Docks built for current and winter conditions.'),('pilings','Steel pilings and covers for demanding conditions.'),('boat-hoists','Lifts and maintenance for river properties.'),('concrete','Flatwork and steps near the waterfront.')],
  faq=('Does river ice damage docks and seawalls in Marine City?','<p>It can. Ice can push on walls, grip pilings and lift or twist them as water levels change. Fall preparation and a spring check-up catch problems early. Read <a href="/blog/michigan-winter-dock-seawall-damage/">how Michigan winters damage docks and seawalls</a>.</p>'),
  near=['algonac','st-clair','marysville']),

 dict(slug='st-clair', name='St. Clair', kind='city', county='St. Clair', water='scr', hero='excavator-barge-timber-pilings',
  lead='St. Clair’s riverfront is a long, public boardwalk edge, and private shoreline here deals with steady river flow and passing freighters.',
  p1='The city of St. Clair fronts the St. Clair River, with Palmer Park and its riverside boardwalk drawing visitors to watch passing ships. NOAA’s Coast Pilot lists current at St. Clair of roughly 1.4 to 2.1 mph depending on river flow, among the higher readings on the lower river.',
  p2='Steady flow makes scour a real design concern for walls and pilings, and freighter wakes and ice add more load. For homeowners, the practical work includes sound anchoring, protected steel, working drainage and periodic inspection. Concrete steps, patios and decks near the river need to shed water and survive freeze-thaw cycles.',
  notes=['St. Clair is in St. Clair County on the St. Clair River.', 'NOAA lists river current at St. Clair at about 1.4 to 2.1 mph, depending on flow.', 'Palmer Park’s riverside boardwalk is a local landmark.'],
  svc=[('seawalls','Repairs and replacements for riverfront walls.'),('pilings','Steel and wood pilings, covers and removal.'),('docks','Docks and structural repairs.'),('concrete','Riverside patios, steps and walks.'),('decks','Waterfront decks in wood, composite and Trex.')],
  faq=('Do freighter wakes affect docks and walls on the St. Clair River in St. Clair?','<p>Large ships pass close to the shore, and their wakes and the steady current add load to walls, pilings and docks. Designs account for that with sound anchoring and appropriately protected materials. Tell us how your frontage is exposed when you request a quote.</p>'),
  near=['marine-city','marysville','algonac']),

 dict(slug='marysville', name='Marysville', kind='city', county='St. Clair', water='scr', hero='covered-marina-walkway-sunset',
  lead='Marysville’s riverfront includes a living shoreline promenade, and the St. Clair River’s current and ice shape what works on private property.',
  p1='Marysville is on the St. Clair River between St. Clair and Port Huron. The city’s riverfront includes Marysville Beach and the Living Shoreline Promenade, and NOAA lists river current at Marysville of roughly 1.3 to 1.9 mph depending on flow.',
  p2='A living shoreline uses plants and natural materials to hold a bank, and regulators often look at softer approaches first. Structural walls, docks and pilings are still the right answer on many lots, especially where current, wakes and ice load the shore. If you are weighing options, EGLE and your city can point you to guidance, and we can talk through the structural side.',
  notes=['Marysville is in St. Clair County on the St. Clair River.', 'Marysville Beach and the Living Shoreline Promenade are on the riverfront.', 'NOAA lists river current at about 1.3 to 1.9 mph, depending on flow.'],
  svc=[('seawalls','Structural walls for riverfront lots.'),('docks','Docks and repairs.'),('pilings','Pilings and covers.'),('excavating-grading','Grading and drainage along river banks.'),('concrete','Patios, steps and walks.')],
  faq=('What is a living shoreline, and do you build them in Marysville?','<p>A living shoreline holds a bank with plants and natural materials instead of a hard wall. Stier’s Construction builds structural seawalls, docks and pilings, so we are the right call when a structure is needed. If you are interested in a soft-shoreline approach, EGLE and your city can point you to guidance.</p>'),
  near=['st-clair','port-huron','marine-city']),

 dict(slug='port-huron', name='Port Huron', kind='city', county='St. Clair', water='scr', hero='winter-dock-edge',
  lead='Port Huron is where Lake Huron drains into the St. Clair River, and the fast water near the Blue Water Bridge is a design factor of its own.',
  p1='Port Huron sits at the head of the St. Clair River, where Lake Huron flows out toward Lake St. Clair. The Blue Water Bridge connects the city to Sarnia, Ontario, and freighters pass close to shore. According to NOAA’s Coast Pilot, a rapids section extends from about 1,000 feet above the bridge to 200 or 300 feet below it.',
  p2='Current is stronger near the head of the river than farther downstream, which raises scour and load concerns for walls, pilings and docks. That favors carefully anchored walls, strong steel and thorough inspection. Away from the fastest water, the same care with drainage, caps and freeze-thaw applies to concrete, decks and steps.',
  notes=['Port Huron is in St. Clair County at the head of the St. Clair River.', 'NOAA notes a rapids section around the Blue Water Bridge.', 'Freighters and other ships pass close to the city’s shoreline.'],
  svc=[('seawalls','Repairs and replacements for river-facing walls.'),('pilings','Steel pilings for demanding current.'),('docks','Docks and structural repairs.'),('welding-fabrication','Steel repairs and custom fabrication.'),('concrete','Flatwork, steps and removal.')],
  faq=('Is the current stronger near the Blue Water Bridge in Port Huron?','<p>Yes. NOAA’s Coast Pilot notes a rapids section extending from about 1,000 feet above the Blue Water Bridge to 200 or 300 feet below it, and current is generally stronger near the head of the river than farther downstream. That affects how walls, pilings and docks are designed and anchored.</p>'),
  near=['marysville','st-clair','marine-city']),

 dict(slug='wyandotte', name='Wyandotte', kind='city', county='Wayne', water='dr', hero='excavator-loading-dump-trailer',
  lead='Wyandotte’s Detroit River shoreline puts seawalls, docks and pilings up against current, shipping traffic and ice.',
  p1='Wyandotte is a Downriver community on the Detroit River in Wayne County, a short distance from Grosse Ile, Trenton and Gibraltar. The Detroit River is a busy commercial shipping route linking Lake St. Clair with Lake Erie, and its current and traffic set the conditions for waterfront structures.',
  p2='Riverfront walls and docks here have to handle steady flow, wakes from large vessels and winter ice. Alongside shoreline work, waterfront owners often need concrete, excavating, grading and demolition: removing an old slab or garage, regrading a yard for drainage, or pouring a new patio.',
  notes=['Wyandotte is in Wayne County on the Detroit River.', 'Grosse Ile, Trenton and Gibraltar are nearby Downriver communities.', 'The Detroit River is a working shipping channel.'],
  svc=[('seawalls','Walls and repairs for river frontage.'),('docks','Docks and structural repairs.'),('pilings','Steel and wood pilings and removal.'),('concrete','New flatwork and removal of old concrete.'),('demolition','Demolition, debris hauling and site cleanup.'),('excavating-grading','Site prep and drainage.')],
  faq=('Which permits apply to dock and seawall work on the Detroit River in Wyandotte?','<p>Work in or over the water generally involves EGLE and the U.S. Army Corps of Engineers, and EGLE district staff can tell you which part of state law applies to your site. Your city’s building department handles local requirements above the waterline. See our <a href="/blog/michigan-permits-seawalls-docks-dredging/">permit guide</a>.</p>'),
  near=['trenton','grosse-ile','gibraltar']),

 dict(slug='trenton', name='Trenton', kind='city', county='Wayne', water='dr', hero='dock-work-through-ice',
  lead='Trenton faces the Trenton Channel of the Detroit River, where channel current, islands and ice affect every dock and wall.',
  p1='Trenton is a Downriver city on the Detroit River’s Trenton Channel, the channel that separates the mainland from Grosse Ile. Elizabeth Park, a 162-acre Wayne County park on the channel, is an artificial island formed when a canal was cut in the nineteenth century.',
  p2='Channel shorelines see current and boat traffic, and sheltered coves and canals add shallow water and silt. Docks, pilings and lifts have to be planned around depth and winter ice, and walls need drainage and anchoring that hold up through freeze-thaw cycles. Dredging can be part of keeping a slip usable.',
  notes=['Trenton is in Wayne County on the Trenton Channel of the Detroit River.', 'Elizabeth Park, on the channel, is a Wayne County park.', 'Grosse Ile lies across the channel.'],
  svc=[('seawalls','Walls and repairs on channel frontage.'),('docks','Docks and repairs.'),('pilings','Pilings and covers.'),('boat-hoists','Lifts and maintenance.'),('dredging','Slip and boat well dredging.')],
  faq=('What is the Trenton Channel, and does it change how my dock is built?','<p>The Trenton Channel is the western channel of the Detroit River, running between the mainland and Grosse Ile. Depth, current, boat traffic and winter ice on your stretch of shoreline decide dock and wall design, so we look at your specific frontage when we quote.</p>'),
  near=['wyandotte','grosse-ile','gibraltar']),

 dict(slug='gibraltar', name='Gibraltar', kind='city', county='Wayne', water='dr', hero='excavator-site-dusk',
  lead='Canals cut through Gibraltar’s shoreline near the mouth of the Detroit River, so seawalls, boat wells and dredging are everyday concerns.',
  p1='Gibraltar is a Downriver city near the southern end of the Detroit River, close to Lake Erie. Several of the islands within the city were created by canals, which means many properties sit on canal frontage or on small islands with their own shorelines.',
  p2='Canal and island lots depend on their walls, and shallow, calm water collects silt over time. Boat wells and slips may need dredging, docks and pilings have to be planned for depth and ice, and walls need drainage and anchoring. Land-side work such as grading and concrete decides where water goes.',
  notes=['Gibraltar is in Wayne County near the mouth of the Detroit River.', 'Several islands within the city were created by canals.', 'Canal lots make seawalls and boat wells central to home maintenance.'],
  svc=[('seawalls','Canal and island walls, repairs and caps.'),('docks','Docks and repairs for canal lots.'),('dredging','Boat well and canal dredging.'),('pilings','Pilings and covers.'),('boat-hoists','Lift installs and maintenance.')],
  faq=('Do canal lots in Gibraltar need dredging?','<p>They can. Calm canal water collects silt, and shallow slips and boat wells are the usual sign. Watch for your boat touching bottom or a lift that no longer lowers clear. See our <a href="/blog/dredging-101-canals-marinas-boat-wells/">dredging guide</a>.</p>'),
  near=['trenton','grosse-ile','rockwood']),

 dict(slug='rockwood', h1='Docks, Riverbank and Site Work in Rockwood, Michigan', title='Rockwood: Docks & Riverbank Work', desc='Docks, riverbank protection, grading, concrete and decks along the Huron River in Rockwood, Michigan. Owner-led crew. Free quotes.', name='Rockwood', kind='city', county='Wayne', water='river', hero='wood-dock-yellow-flag',
  lead='Rockwood’s waterfront is on the Huron River, which empties into Lake Erie, so river banks, docks and drainage lead the project list.',
  p1='Rockwood is a Wayne County city on the Huron River, which flows on to Lake Erie. Riverfront properties here deal with banks that can erode, docks that must handle changing river levels, and drainage that has to run off the land without washing soil into the water.',
  p2='Rivers that flow into the Great Lakes are often regulated as streams under a different part of Michigan’s environmental law than the Great Lakes shoreline itself, so check with EGLE about which rules apply to your site before you plan. On the land side, grading, concrete and decks are common companions to riverfront work.',
  notes=['Rockwood is in Wayne County on the Huron River.', 'The Huron River empties into Lake Erie downstream.', 'Riverbank stabilization, docks and drainage are typical projects.'],
  svc=[('docks','Docks and repairs for river properties.'),('seawalls','Bank stabilization and walls where a structure is appropriate.'),('excavating-grading','Grading and drainage that protect the bank.'),('concrete','Patios, drives and walks.'),('decks','Riverside decks.')],
  faq=('Is a dock permit on the Huron River different from a Great Lakes dock permit?','<p>It can be. Rivers that flow into the Great Lakes are often regulated as streams, while the Great Lakes shoreline itself is regulated separately. EGLE can tell you which rules apply at your address, and permits are applied for through the MiEnviro Portal. See our <a href="/blog/michigan-permits-seawalls-docks-dredging/">permit guide</a>.</p>'),
  near=['gibraltar','trenton','monroe']),

 dict(slug='monroe', name='Monroe', kind='city', county='Monroe', water='erie', hero='l-shaped-dock-choppy-water',
  lead='Monroe is Michigan’s only Lake Erie port city, with the River Raisin running through town and shallow, exposed water at its mouth.',
  p1='Monroe sits on the west shore of Lake Erie at the mouth of the River Raisin, and the Port of Monroe is the only port in Michigan on Lake Erie. The river winds through downtown, and Sterling State Park brings the lakeshore to the edge of the city. Monroe County has nearly 30 miles of Lake Erie shoreline.',
  p2='Lake Erie exposure means waves and water-level swings, and the lower River Raisin channel needs ongoing dredging for ship traffic, according to the city. Private docks, walls and pilings here have to allow for open-water waves, river current and sediment. Permit rules differ between the Lake Erie shoreline and the river, so confirm with EGLE which apply to your site.',
  notes=['Monroe is in Monroe County on Lake Erie at the mouth of the River Raisin.', 'The Port of Monroe is Michigan’s only port on Lake Erie.', 'Sterling State Park is on the lakeshore.'],
  svc=[('docks','Docks and repairs for river and lake properties.'),('seawalls','Walls and bank protection.'),('pilings','Steel and wood pilings and covers.'),('dredging','Slip, boat well and canal dredging.'),('boat-hoists','Lifts and maintenance.'),('concrete','Flatwork and removal.')],
  faq=('Does the River Raisin need dredging, and does that affect private docks in Monroe?','<p>According to the city, the lower River Raisin channel needs ongoing dredging for ship traffic. Private slips and boat wells can silt in over time too, and dredging in Great Lakes waters generally needs permits. See our <a href="/blog/dredging-101-canals-marinas-boat-wells/">dredging guide</a>.</p>'),
  near=['rockwood','gibraltar','trenton']),
]
TOWN_BY_SLUG = {t['slug']: t for t in TOWNS}
